repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.3  # Should match pyproject.toml
    hooks:
      - id: ruff
        name: ruff common
        args: ['--fix']
      - id: ruff-format
