[tool.black]
line-length = 99
target-version = ["py38", "py39", "py310", "py311", "py312"]

[tool.isort]
profile = "black"
known_local_folder = ["gpuhunt", "tests", "integrity_tests"]
line_length = 99
