name: Test package

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Run isort
        uses: isort/isort-action@master
        with:
          isort-version: 5.12.0
          configuration: "--settings-file pyconfig.toml --check-only --diff"
          sort-paths: "src"
      - name: Run black
        uses: psf/black@stable
        with:
          options: "--config pyconfig.toml --check --verbose"
          src: "./src"
          version: "~= 23.0"

  python-test:
    needs: [ python-lint ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.8, 3.9, "3.10", 3.11 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements_dev.txt
      - name: Run pytest
        run: |
          pytest src/tests
